config/routes.rb
Rails.application.routes.draw do
  resources :adresses
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root 'welcome#home'
  get 'about', to: 'welcome#about'
  
  resources :articles
  
  get 'signup', to: "users#new"
  resources :users, except: [:new]
  get 'login', to: "sessions#new"
  post 'login', to: "sessions#create"
  delete 'logout', to: "sessions#destroy"
  
  resources :categories, except: [:destroy]
end

app/controllers/adresses_controller.rb
class AdressesController < ApplicationController
  before_action :set_adress, only: [:show, :edit, :update, :destroy]

  # GET /adresses
  # GET /adresses.json
  def index
    @adresses = Adress.all
  end

  # GET /adresses/1
  # GET /adresses/1.json
  def show
  end

  # GET /adresses/new
  def new
    @adress = Adress.new
  end

  # GET /adresses/1/edit
  def edit
  end

  # POST /adresses
  # POST /adresses.json
  def create
    @adress = Adress.new(adress_params)

    respond_to do |format|
      if @adress.save
        format.html { redirect_to @adress, notice: 'Adress was successfully created.' }
        format.json { render :show, status: :created, location: @adress }
      else
        format.html { render :new }
        format.json { render json: @adress.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /adresses/1
  # PATCH/PUT /adresses/1.json
  def update
    respond_to do |format|
      if @adress.update(adress_params)
        format.html { redirect_to @adress, notice: 'Adress was successfully updated.' }
        format.json { render :show, status: :ok, location: @adress }
      else
        format.html { render :edit }
        format.json { render json: @adress.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /adresses/1
  # DELETE /adresses/1.json
  def destroy
    @adress.destroy
    respond_to do |format|
      format.html { redirect_to adresses_url, notice: 'Adress was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_adress
      @adress = Adress.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def adress_params
      params.require(:adress).permit(:street_name)
    end
end

app/helpers/adresses_helper.rb
module AdressesHelper
end

app/views/adresses/_form.html.erb
<%= form_with(model: adress, local: true) do |form| %>
  <% if adress.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(adress.errors.count, "error") %> prohibited this adress from being saved:</h2>

      <ul>
      <% adress.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :street_name %>
    <%= form.text_field :street_name, id: :adress_street_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/adresses/edit.html.erb
<h1>Editing Adress</h1>

<%= render 'form', adress: @adress %>

<%= link_to 'Show', @adress %> |
<%= link_to 'Back', adresses_path %>

app/views/adresses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Adresses</h1>

<table>
  <thead>
    <tr>
      <th>Street name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @adresses.each do |adress| %>
      <tr>
        <td><%= adress.street_name %></td>
        <td><%= link_to 'Show', adress %></td>
        <td><%= link_to 'Edit', edit_adress_path(adress) %></td>
        <td><%= link_to 'Destroy', adress, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Adress', new_adress_path %>

app/views/adresses/new.html.erb
<h1>New Adress</h1>

<%= render 'form', adress: @adress %>

<%= link_to 'Back', adresses_path %>

app/views/adresses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Street name:</strong>
  <%= @adress.street_name %>
</p>

<%= link_to 'Edit', edit_adress_path(@adress) %> |
<%= link_to 'Back', adresses_path %>